### ISSUE TITLE
Fresh install of 0.4.3 from Hackage fails

### ISSUE THREAD

**Issue by alex-ball** [gsdlab/clafer#83]
Having installed cabal-install-1.22 and ghc-7.10.3, I set up a Cabal sandbox and followed the instructions for installing with cabal-install, namely:

    cabal update
    cabal install alex happy
    cabal install clafer

Installation failed with the message:

    src/Language/Clafer/Front/LexClafer.x:188:38:
        Not in scope: ‘ord’
        Perhaps you meant one of these:
          ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
          ‘ord#’ (imported from GHC.Exts)
    Failed to install clafer-0.4.3

Should this file explicitly `import Data.Char (ord)`?

**Comment by mantkiew** [comment]
Hi,That's always a problem with cabal - the builds are not reproducible after Hackage changes (new versions of packages, etc.). I am no longer using cabal for development. I highly recommend using stack for building. Just use make - Clafer contains a Makefile which calls stack. Michał                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Alex BallSent: Tuesday, March 22, 2016 10:55 AMTo: gsdlab/claferReply To: gsdlab/claferSubject: [clafer] Fresh install of 0.4.3 from Hackage fails (#83)Having installed cabal-install-1.22 and ghc-7.10.3, I set up a Cabal sandbox and followed the instructions for installing with cabal-install, namely:

cabal update
cabal install alex happy
cabal install clafer


Installation failed with the message:

src/Language/Clafer/Front/LexClafer.x:188:38:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)
Failed to install clafer-0.4.3


Should this file explicitly import Data.Char (ord)?

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by mantkiew** [comment]
Just pushed a [commit](505996d4b1c0b327fb1bfd6e3c595dc92ec7ddac) fixing building with GHC 7.10.3 to the branch `develop`.
